### ISSUE TITLE
Question about the executive time

### ISSUE THREAD

**Issue by liwenwei123** [vc-nju/RAS_python#1]
Hello！Thanks for your work!
I can run the train code successfully, but it spent more than 24 hours to train 100 epochs.But in the paper it said the executive time is 2 hours.Could you tell me how long you use to train the model?Is the time i spent normally because it's a pytorch version?
Thanks you very much!

**Comment by lizhihao6** [comment]
It might because of the dataloader. Could you run 'nvidia-smi -l' and let me know about the info of GPU usage.

**Comment by liwenwei123** [comment]
> It might because of the dataloader. Could you run 'nvidia-smi -l' and let me know about the info of GPU usage.

Thank you for your reply.This is the info of my gpu.
In my record it cost 0.095s for an inference.About 10fps +.Still less than the 40fps+ in the paper.


Wed Apr 22 09:53:44 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:18:00.0 Off |                    0 |
| N/A   42C    P0    28W /  70W |   4754MiB / 15079MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:19:00.0 Off |                    0 |
| N/A   70C    P0    71W /  70W |   3835MiB / 15079MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:5E:00.0 Off |                    0 |
| N/A   68C    P0    71W /  70W |   3835MiB / 15079MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:5F:00.0 Off |                    0 |
| N/A   74C    P0    71W /  70W |   3835MiB / 15079MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla T4            Off  | 00000000:AF:00.0 Off |                    0 |
| N/A   64C    P0    70W /  70W |   3835MiB / 15079MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla T4            Off  | 00000000:B0:00.0 Off |                    0 |
| N/A   64C    P0    70W /  70W |   3835MiB / 15079MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla T4            Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   70C    P0    71W /  70W |   3835MiB / 15079MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla T4            Off  | 00000000:D9:00.0 Off |                    0 |
| N/A   70C    P0    70W /  70W |   3835MiB / 15079MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by lizhihao6** [comment]
Hi, I have tested it on my gpu(1080Ti), it cost about 0.03x s/per 512x512 image. Have you tested it with torch.no_grad()? And please do not count the time that copy the tensor from cpu to gpu。

**Comment by liwenwei123** [comment]
@lizhihao6 Hello, I followed your advice and changed the gpu from Tesla T4 to TITAN Xp, and now it cost 0.0334xs /per image.Maybe the main reason for the slow inference was the server performance.
Thanks for your advice~
